### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by chrswt** [tuna-io/tuna-io#15]
- [X] Set up testing framework (merged with PR #35)
- [X] Set up continuous integration framework (e.g. circle CI or something similar for continuous integration tests on every pull request) (merged with PR #36)
- [x] Set up process to automatically integrate new tests (Note: this requires editing the Gruntfile and having CircleCI call NPM test)
- [x] Set up documentation for testing framework

**Comment by ghost** [comment]
Currently blocked on Gruntfile set up

**Comment by BillZito** [comment]
Should be resolved with #38
