### ISSUE TITLE
User endpoint and authentication

### ISSUE THREAD

**Issue by BillZito** [tuna-io/tuna-io#3]
- [x] Research tokens (JWT or otherwise, research Redis session management also) in Go
- [x] Login: take username / password and send back token
- [x] Signup: take username / password and send back token
- [x] Hash passwords
- [x] Send to DB
- [x] Logout: delete stored token

**Comment by chrswt** [comment]
- [Gorilla Secure Cookies](http://www.gorillatoolkit.org/pkg/securecookie)
- [Gorilla Sessions](http://www.gorillatoolkit.org/pkg/sessions)
