### ISSUE TITLE
Dashboard component

### ISSUE THREAD

**Issue by chrswt** [tuna-io/tuna-io#4]
Mandatory user stories:
- [x] Video upload button
- [x] Able to upload videos
- [x] Selection options: checkbox for transcript generation and highlight reel generation
- [ ] Progress bar
- [ ] Render video preview after upload is complete
- [x] See other uploaded videos
- [x] See watch history
- [x] Connect to profile management

**Comment by BillZito** [comment]
@showmethewei is this complete?

**Comment by ghost** [comment]
@chrswt Nope. A few of these are extensions that no longer make sense for the MVP
